name: Bygg og publiser docker-image for master

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-on-master:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Distribute workflowese
        run: |
          ./distribute_workflows.sh
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          WORKFLOW_DIRECTORY: "common_workflows"
          TEAM_NAME: "personbruker"
          INCLUDE: "chris-santa/testservant"
          EXCLUDE: "varselinnboks saksoversikt"




