name: Bygg og publiser docker-image for master

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-on-master:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: git debug
        run: |
          PAYLOAD='{ "message": "Postman creator", "content": "VGhpcyBpcyBhIGZpbGUgY3JlYXRlZCBmcm9tIHBvc3RtYW4u" }'
          curl -u "$GITHUB_TOKEN:" --data-urlencode $PAYLOAD https://api.github.com/repos/chris-santa/testservant/contents/newfolder/othernew.txt


